title: Code Cumbria
email: hello@codecumbria.org
description: Unearthing rural tech
baseurl: "" # the subpath of your site, e.g. /blog
url: https://codecumbria.org
twitter_username: codecumbria
github_username:  codecumbria

# Build settings
markdown: kramdown
theme: jekyll-theme-hydeout
remote_theme: fongandrew/hydeout
paginate: 5
excerpt_separator: <!--more-->
google_analytics: UA-44733760-1

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

